### ISSUE TITLE
Compiling go in JetsonTX1 64 bits

### ISSUE THREAD

**Issue by eddytrex** [jetsonhacks/compileGolang#1]
Hi, maybe is no an issue but, I need some help. 
I was trying to compile with the script  compileGolangArm64.sh. But throw this error: 

``` bash
_check_for_64_bit_pointer_matching_GoInt' is negative
 typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];
```

first I think was the Arch, but to me seems ok 

``` bash
 $ uname -m
aarch64
```

Thanks.

**Comment by jetsonhacks** [comment]
Both the 32 bit version of L4T and the 64 bit version of L4T report back as aarch64. 

Are you using 32 bit L4T? If so, compileGolangArm32.sh is the one to use. I would try that first.
If you have 64 bit L4T installed, then indeed compileGolangArm64.sh is correct.

**Comment by eddytrex** [comment]
It works with Arm32. 
Thanks
